services:
  voicevox_bot:
    build: .
    container_name: voicevox_bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - VOICEVOX_API_URL=${VOICEVOX_API_URL}
      - DEFAULT_SPEAKER_ID=${DEFAULT_SPEAKER_ID}
      - MAX_UTTERANCE_LENGTH=${MAX_UTTERANCE_LENGTH}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_KEY=${API_KEY}
      - API_HOST=0.0.0.0
      - PORT=${PORT}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./:/app
    depends_on:
      - voicevox_engine
    command:
      sh -c "npm install -g npm && npm install && npm run deploy:commands && npm run dev"
  
  voicevox_engine:
    image: voicevox/voicevox_engine:latest
    container_name: voicevox_engine
    restart: unless-stopped
    ports:
      - "50021:50021"
